window.SLIDES = [
  { "kind": "cover",
    "title": "Digital Sabotage",
    "byline": "Grayson Earle, Akademie Schloss Solitude Web Residency",
    "note": "post-awareness" },

  { "kind": "textimg",
    "title": "SABOTAGE",
    "sub": "a brief etymology",
    "body": [
      "from sabot, the wooden clog of the French worker. the story goes that workers threw their clogs into factory machinery to jam the gears and stop production. historians dispute whether clogs were ever really thrown, but the word stuck: stopping the machine from the inside.",
      "redneck, too, is said to come from a worker's garment, the red bandana coal miners wore as a sign of solidarity in the twentieth century."
    ],
    "src": "media/sabotage-etymology.png",
    "note": "sabotage-etymology" },

  { "kind": "image", "src": "media/other-work-montage.jpg",
    "caption": "and other things",
    "note": "other-work" },

  { "kind": "video", "src": "media/hand-learning.mp4", "poster": "media/hand-learning-poster.jpg",
    "caption": "training robots how to give the finger",
    "note": "other-work" },

  { "kind": "section",
    "title": "Mass Action",
    "sub": "turning a crowd into the weapon",
    "note": "mass-action" },
  { "kind": "image", "src": "media/floodnet.jpg",
    "caption": "Ricardo Dominguez: FloodNet",
    "note": "floodnet" },
  { "kind": "image", "src": "media/etoy.jpg",
    "caption": "eToy War (®TMark, 1999)",
    "note": "etoy-war" },
  { "kind": "image", "src": "media/domestic-tension-install.png",
    "caption": "Wafaa Bilal: Domestic Tension (Shoot an Iraqi), 2007",
    "note": "domestic-tension" },
  { "kind": "video", "src": "media/domestic-tension.mp4", "poster": "media/domestic-tension-poster.jpg",
    "caption": "Domestic Tension in operation",
    "note": "domestic-tension" },
  { "kind": "section",
    "title": "Impersonation",
    "sub": "wearing an institution's own authority against it",
    "note": "impersonation" },
  { "kind": "video", "src": "media/barbie-liberation.mp4", "poster": "media/barbie-liberation-poster.jpg",
    "caption": "Barbie Liberation Organization news coverage (1993)",
    "note": "barbie-liberation" },
  { "kind": "image", "src": "media/yes-men.jpg",
    "caption": "The Yes Men: the Dow Chemical hoax, BBC World (2004)",
    "note": "yes-men" },
  { "kind": "video", "src": "media/yes-men-bbc.mp4", "poster": "media/yes-men-bbc-poster.jpg",
    "caption": "\"Jude Finisterra\" on BBC World",
    "note": "yes-men" },
  { "kind": "image", "src": "media/white-collar-crime-risk-zones.jpg",
    "caption": "White Collar Crime Risk Zones (Sam Lavigne, Francis Tseng & Brian Clifton, 2017)",
    "link": "https://whitecollar.thenewinquiry.com/",
    "note": "white-collar-crime" },
  { "kind": "section",
    "title": "Automation",
    "sub": "handing the act of sabotage itself to a machine",
    "note": "automation" },
  { "kind": "video", "src": "media/contestational-robotics.mp4", "poster": "media/contestational-robotics-poster.jpg",
    "caption": "Contestational Robotics (Institute for Applied Autonomy, 2003)",
    "note": "contestational-robotics" },
  { "kind": "image", "src": "media/adnauseam-vault.png",
    "caption": "AdNauseam (Daniel C. Howe, Helen Nissenbaum & Mushon Zer-Aviv, 2014)",
    "note": "adnauseam" },
  { "kind": "image", "src": "media/synthetic-messenger.jpg",
    "caption": "Tega Brain & Sam Lavigne: Synthetic Messenger (2021)",
    "note": "synthetic-messenger" },
  { "kind": "video", "src": "https://player.vimeo.com/video/561052061?quality=1080p&dnt=1&title=0&byline=0&portrait=0",
    "caption": "Synthetic Messenger Excerpts",
    "note": "synthetic-messenger" },
  { "kind": "image", "src": "media/abortion-drone.jpg",
    "caption": "Abortion Drone (Women on Waves, 2015), documented by Laia Abril",
    "note": "abortion-drone" },
  { "kind": "image", "src": "media/seti.png",
    "caption": "SETI@home",
    "note": "seti" },
  { "kind": "image", "src": "media/bailbloc-interface.png", "caption": "",
    "note": "bail-bloc" },
  { "kind": "image", "src": "media/bailbloc-report.png", "caption": "",
    "note": "bail-bloc" },
  { "kind": "image", "src": "media/first-check.png",
    "caption": "First check cut to BFF, 2017",
    "note": "bail-bloc" },

  { "kind": "section",
    "title": "Tax Avoidance",
    "sub": "turning the tax code itself into material",
    "note": "tax-avoidance" },
  { "kind": "image", "src": "media/loophole-for-all.jpg",
    "caption": "Paolo Cirio: Loophole for All (2013)",
    "note": "loophole-for-all" },
  { "kind": "image", "src": "media/tax-deductible.png",
    "caption": "Tax Deductible Expenses, 2017",
    "note": "tax-deductible" },
  { "kind": "image", "src": "media/bvg-fine-receipt.jpg",
    "caption": "60€ Fine Incurred for Riding Transit Without a Ticket in Berlin, 2024",
    "note": "bvg-fine" },
  { "kind": "image", "src": "media/bvg-fine-superrare.png",
    "caption": "NFT listing on SuperRare",
    "note": "bvg-fine" },
  { "kind": "image", "src": "media/bvg-fine-dubai.jpg",
    "caption": "Exhibition view at Dubai Design Week 2024, pictured with friend Mohsen Hazrati",
    "note": "bvg-fine" },
  { "kind": "section",
    "title": "Hardware",
    "sub": "objects built to be carried and deployed",
    "note": "hardware" },
  { "kind": "image", "src": "media/tripwire.png",
    "caption": "Tad Hirsch: Tripwire (2006)",
    "note": "tripwire" },
  { "kind": "image", "src": "media/log-jammer.jpg",
    "caption": "Allison Burtch: Log Jammer (2014)",
    "note": "log-jammer" },
  { "kind": "image", "src": "media/work-clock.png",
    "caption": "79% Work Clock (Disobedient Electronics, PARTY)",
    "note": "work-clock" },
  { "kind": "side",
    "src": ["media/transparency-grenade-1.png", "media/transparency-grenade-2.png"],
    "caption": "Julian Oliver: Transparency Grenade (2012)",
    "note": "transparency-grenade" },
  { "kind": "video", "src": "media/reflecto-cube.mp4", "poster": "media/reflecto-cube.jpg",
    "caption": "Reflecto Cube (Colectivo Enmedio, 2012-ongoing)",
    "note": "reflecto-cube" },

  { "kind": "section",
    "title": "Labor",
    "sub": "refusing full productivity, unwaged work, scab hiring",
    "note": "labor" },
  { "kind": "image", "src": "media/slow-hot-computer.png",
    "caption": "Sam Lavigne: Slow Hot Computer (2015)",
    "note": "slow-hot-computer" },
  { "kind": "image", "src": "media/wages-for-facebook.jpg",
    "caption": "Laurel Ptak: Wages for Facebook (2014)",
    "link": "http://wagesforfacebook.com/",
    "note": "wages-for-facebook" },
  { "kind": "video", "src": "media/kelloggs-hack.mp4", "poster": "media/kelloggs-hack.jpg",
    "caption": "Kellogg's Hack (Sean Black, @black_madness21, 2021)",
    "note": "kelloggs-hack" },

  { "kind": "text",
    "title": "thanks!",
    "body": [
      "@prismspecs",
      "graysonearle.com"
    ] }
];
