window.SLIDES = [
  { "kind": "cover",
    "title": "Digital Sabotage",
    "subtitle": "speculative tools for digital monkeywrenching and workplace sabotage",
    "byline": "Grayson Earle · Akademie Schloss Solitude Web Residency" },

  { "kind": "image", "src": "media/monkey-wrench-gang.png",
    "caption": "The Monkey Wrench Gang — Edward Abbey (1975)" },
  { "kind": "image", "src": "media/may-day.png",
    "caption": "May Day" },
  { "kind": "image", "src": "media/floodnet.jpg",
    "caption": "Ricardo Dominguez — FloodNet" },
  { "kind": "image", "src": "media/etoy.jpg",
    "caption": "eToy War — ®TMark (1996)" },
  { "kind": "image", "src": "media/tripwire.png",
    "caption": "Tad Hirsch — Tripwire (2006)" },
  { "kind": "image", "src": "media/contestational-robotics.jpg",
    "caption": "Contestational Robotics — Institute for Applied Autonomy (2003)" },
  { "kind": "image", "src": "media/seti.png",
    "caption": "SETI@home" },
  { "kind": "image", "src": "media/bailbloc-interface.png", "caption": "" },
  { "kind": "image", "src": "media/bailbloc-report.png", "caption": "" },
  { "kind": "image", "src": "media/first-check.png",
    "caption": "First check cut to BFF, 2017" },
  { "kind": "image", "src": "media/tax-deductible.png",
    "caption": "Tax Deductible Expenses, 2017" },
  { "kind": "image", "src": "media/haacke-performance.png",
    "caption": "A homage to Hans Haacke — performance/intervention (2020), Artists for Workers (Grayson Earle & “M”)" },

  { "kind": "side",
    "src": ["media/haacke-moma-poll-1.png", "media/haacke-moma-poll-2.png"],
    "caption": "Hans Haacke's MoMA Poll (1970)" },
  { "kind": "image", "src": "media/haacke-plaque.png",
    "caption": "plaque for Hans Haacke's new work at New Museum" },
  { "kind": "image", "src": "media/haacke-ipad-surveys.png",
    "caption": "iPad surveys for Hans Haacke's new work at New Museum" },
  { "kind": "image", "src": "media/haacke-ipad-survey.png",
    "caption": "iPad survey for Hans Haacke's new work at New Museum" },
  { "kind": "image", "src": "media/haacke-survey-results-1.png",
    "caption": "survey results for Hans Haacke's new work at New Museum" },
  { "kind": "image", "src": "media/haacke-survey-results-2.jpg",
    "caption": "survey results for Hans Haacke's new work at New Museum" },
  { "kind": "image", "src": "media/haacke-survey-booklets-1.jpg",
    "caption": "survey booklets for Hans Haacke's new work at New Museum" },
  { "kind": "image", "src": "media/haacke-q14-before.png",
    "caption": "survey question #14 (before)" },
  { "kind": "side",
    "src": ["media/haacke-survey-booklets-2.jpg", "media/haacke-survey-booklets-3.jpg"],
    "caption": "survey booklets for Hans Haacke's new work at New Museum" },
  { "kind": "video", "src": "https://www.youtube.com/embed/28VtJpJk-_4?quality=1080p&rel=0&modestbranding=1",
    "caption": "automated Hans Haacke survey bot (2021)" },
  { "kind": "side",
    "src": ["media/haacke-survey-results-2.jpg", "media/haacke-before-after-2.jpg"],
    "caption": "before, after" },
  { "kind": "image", "src": "media/haacke-q14-after.png",
    "caption": "survey question #14 (after)" },

  { "kind": "gallery",
    "src": ["media/press-1.png", "media/press-2.png", "media/press-3.png", "media/press-4.png", "media/press-badge.png"],
    "caption": "press" },
  { "kind": "image", "src": "media/bailbloc-nyt.png", "caption": "" },
  { "kind": "image", "src": "media/slow-hot-computer.png",
    "caption": "Sam Lavigne — Slow Hot Computer (2015)" },
  { "kind": "image", "src": "media/synthetic-messenger.jpg",
    "caption": "Tega Brain & Sam Lavigne — Synthetic Messenger (2021)" },

  { "kind": "video", "src": "https://player.vimeo.com/video/561052061?quality=1080p&dnt=1&title=0&byline=0&portrait=0",
    "caption": "Synthetic Messenger Excerpts" },

  { "kind": "textimg",
    "title": "SABOTAGE",
    "sub": "a brief etymology",
    "body": [
      "from sabot — the wooden clog of the French worker. the story goes that workers threw their clogs into factory machinery to jam the gears and stop production. historians dispute whether clogs were ever really thrown, but the word stuck: stopping the machine from the inside.",
      "redneck, too, is said to come from a worker's garment — the red bandana coal miners wore as a sign of solidarity in the twentieth century."
    ],
    "src": "media/sabotage-etymology.png" },

  { "kind": "image", "src": "media/work-clock.png",
    "caption": "79% Work Clock — Disobedient Electronics, PARTY" },
  { "kind": "side",
    "src": ["media/transparency-grenade-1.png", "media/transparency-grenade-2.png"],
    "caption": "Julian Oliver — Transparency Grenade (2012)" },
  { "kind": "video", "src": "media/reflecto-cube.mp4", "poster": "media/reflecto-cube.jpg",
    "caption": "Reflecto Cube — Colectivo Enmedio (2012–ongoing)" },
  { "kind": "video", "src": "media/kelloggs-hack.mp4", "poster": "media/kelloggs-hack.jpg",
    "caption": "Kellogg's Hack — Sean Black (@black_madness21) (2021)" },

  { "kind": "text",
    "title": "workplace objects",
    "body": [
      "water coolers — a symbolic meeting point, maybe the coffee area. a good fit for a discussion on wage transparency.",
      "the internet — is there a firewall preventing outside chat platforms?",
      "the power system — power-line networking as a means to be occupied.",
      "video conferencing — what if we introduced a three-second delay?"
    ] },

  { "kind": "image", "src": "media/speculate.png", "caption": "" },

  { "kind": "text",
    "title": "speculate",
    "body": [
      "activity: design a speculative technology, device, artifact, or installation that assists workers in workplace refusal, or otherwise enacts justice for workers. it can be practical, experimental, absurd. it's meant to be imaginative and flexible.",
      "get into random teams of four-ish",
      "you can come up with one idea or multiple ideas",
      "just meant to be a brainstorm, sketching ideas on paper",
      "if you want to prototype 3d objects with paper that's cool, but not necessary"
    ] },

  { "kind": "text",
    "title": "thanks!",
    "body": [
      "@prismspecs (ig)",
      "www.graysonearle.com"
    ] }
];
